"""Reusable, presentation-independent ingestion contracts and adapters."""

from haralens.ingestion.contracts import IngestionAdapter
from haralens.ingestion.csv import CsvIngestionAdapter
from haralens.ingestion.errors import (
    ArchiveSafetyError,
    ColumnLimitExceededError,
    DuplicateColumnsError,
    EmptySourceError,
    EmptyWorksheetError,
    IngestionConsistencyError,
    IngestionError,
    InvalidColumnNamesError,
    InvalidEncodingError,
    MalformedParquetError,
    MalformedSourceError,
    MalformedWorkbookError,
    NoDataRowsError,
    NoUsableWorksheetError,
    ParquetLimitExceededError,
    RowLimitExceededError,
    SourceTooLargeError,
    UnsupportedParquetSchemaError,
    UnsupportedSourceError,
    UnsupportedWorkbookFormatError,
    UnsupportedWorksheetStructureError,
    WorkbookLimitExceededError,
    WorksheetNotFoundError,
    WorksheetSelectionRequiredError,
)
from haralens.ingestion.models import (
    ExcelFormatMetadata,
    IngestionMetadata,
    IngestionRequest,
    IngestionResult,
    ParquetFormatMetadata,
    ResourceLimits,
    SourceType,
)
from haralens.ingestion.parquet import ParquetIngestionAdapter
from haralens.ingestion.xlsx import XlsxIngestionAdapter

__all__ = [
    "ArchiveSafetyError",
    "CsvIngestionAdapter",
    "ColumnLimitExceededError",
    "DuplicateColumnsError",
    "EmptySourceError",
    "EmptyWorksheetError",
    "ExcelFormatMetadata",
    "IngestionAdapter",
    "IngestionConsistencyError",
    "IngestionError",
    "IngestionMetadata",
    "IngestionRequest",
    "IngestionResult",
    "InvalidColumnNamesError",
    "InvalidEncodingError",
    "MalformedParquetError",
    "MalformedSourceError",
    "MalformedWorkbookError",
    "NoDataRowsError",
    "NoUsableWorksheetError",
    "ParquetFormatMetadata",
    "ParquetIngestionAdapter",
    "ParquetLimitExceededError",
    "ResourceLimits",
    "RowLimitExceededError",
    "SourceType",
    "SourceTooLargeError",
    "UnsupportedParquetSchemaError",
    "UnsupportedSourceError",
    "UnsupportedWorkbookFormatError",
    "UnsupportedWorksheetStructureError",
    "WorkbookLimitExceededError",
    "WorksheetNotFoundError",
    "WorksheetSelectionRequiredError",
    "XlsxIngestionAdapter",
]
